version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=register
      - RABBITMQ_DEFAULT_PASS=register
    ports:
      - 5672:5672
      - 15672-15672
    volumes:
      - ~/docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/docker-conf/rabbitmq/log/:/var/rabbitmq

    networks:
      - rabbitmq-network
networks:
  rabbitmq-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
