import { ConsumeQueueCreateRegisterUpdateController } from "./useCase/consumeQueueCreatRegisterUpdateRequest/consumeQueueCreatRegisterUpdateRequestController"
import { ConsumeQueueCreatRegisterUpdateRequestUseCase } from "./useCase/consumeQueueCreatRegisterUpdateRequest/consumeQueueCreatRegisterUpdateRequestUseCase";
import { CreateRegisterUpdateRequestRepository } from "./repository/CreatRegisterUpdateRequestRepository";


let createRegisterUpdateRequestRepository = new CreateRegisterUpdateRequestRepository()
let consumeQueueCreatRegisterUpdateRequestUseCase = new ConsumeQueueCreatRegisterUpdateRequestUseCase(createRegisterUpdateRequestRepository)
let consumeQueueCreatRegisterUpdateController = new ConsumeQueueCreateRegisterUpdateController(consumeQueueCreatRegisterUpdateRequestUseCase)

consumeQueueCreatRegisterUpdateController.Handle()
