version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.1.0
    container_name: elasticsearch
    ports:
      - '9200:9200'
    networks:
      - elastic-network
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:8.1.0
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: https://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["https://elasticsearch:9200"]'
    networks:
      - elastic-network

  # logstash:
  #   image: logstash:8.1.0
  #   container_name: logstash
  #   ports:
  #     - '5000:5000'
  #   networks:
  #     - elastic-network
  #   volumes:
  #     - type: bind
  #       source: ./logstash_pipeline/
  #       target: /usr/share/logstash/pipeline
  #       read_only: true

  logColector:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: ubuntu
    container_name: logColector
    ports:
      - "5250:5250"
    networks:
      - elastic-network
    volumes:
      - ../logs:/var/log/
    depends_on:
      - elasticsearch

networks:
  elastic-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
